# Generated by Django 6.0.6 on 2026-06-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cat_image', models.ImageField(upload_to='category/%Y-%m-%d')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
